//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insendlu.Entities.MySqlConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class wifi
    {
        public int id { get; set; }
        public Nullable<int> worklog_id { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<int> cost { get; set; }
        public Nullable<System.DateTime> end_start { get; set; }
        public Nullable<int> project_id { get; set; }
    }
}
