//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Activity
{
    public Nullable<int> worklog_id { get; set; }
    public string asset { get; set; }
    public Nullable<int> asset_id { get; set; }
    public long id { get; set; }
    public string cost { get; set; }
    public string location_name { get; set; }
    public string material_name { get; set; }
    public string material_quantity { get; set; }
}
