//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class CV
{
    public int id { get; set; }
    public string name { get; set; }
    public string surname { get; set; }
    public string credentials { get; set; }
    public string position { get; set; }
    public string responsibilities { get; set; }
    public string qualification { get; set; }
}
