//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ProjectProjection
{
    public int id { get; set; }
    public Nullable<int> proj_id { get; set; }
    public string employees { get; set; }
    public string vehicle { get; set; }
    public string accomodation { get; set; }
    public string print_material { get; set; }
    public string refreshments { get; set; }
    public string telephone { get; set; }
    public string wifi_data { get; set; }
    public Nullable<int> status { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> modified_at { get; set; }
    public Nullable<int> user_id { get; set; }
}
