//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ProjectScopeOfWork
{
    public long id { get; set; }
    public Nullable<int> proj_id { get; set; }
    public string content { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> modified_at { get; set; }
    public string aim { get; set; }
    public string purpose { get; set; }
    public string deliverables { get; set; }
}
