//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Reference
{
    public int id { get; set; }
    public string client_name { get; set; }
    public string project_details { get; set; }
    public string date_undertaken { get; set; }
    public string project_value { get; set; }
    public string contact_id { get; set; }
    public Nullable<bool> show_value { get; set; }
}
