//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class ReferenceContact
{
    public int id { get; set; }
    public string fullname { get; set; }
    public string position { get; set; }
    public string contact_number { get; set; }
    public string email { get; set; }
    public string address { get; set; }
}
