//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Task
{
    public long id { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> modified_at { get; set; }
    public string body { get; set; }
    public Nullable<int> user_id { get; set; }
    public Nullable<int> task_document_id { get; set; }
    public Nullable<int> status { get; set; }
    public Nullable<int> assigned_to { get; set; }
    public Nullable<System.DateTime> due_date { get; set; }
}
