//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Telephone
{
    public int worklog_id { get; set; }
    public Nullable<System.DateTime> start_date { get; set; }
    public Nullable<System.DateTime> end_start { get; set; }
    public Nullable<int> cost { get; set; }
    public int id { get; set; }
    public Nullable<int> project_id { get; set; }
}
